# Generated by Django 3.1.7 on 2021-04-01 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('restock_level', models.IntegerField()),
                ('unit_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('custname', models.CharField(max_length=150)),
                ('custid', models.IntegerField()),
                ('complete', models.BooleanField()),
                ('paid', models.BooleanField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('stocklevel', models.IntegerField()),
                ('ingredient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredients')),
                ('menu_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder', models.CharField(max_length=50)),
                ('cardnumber', models.CharField(max_length=19)),
                ('cardexpiry', models.CharField(max_length=5)),
                ('cardverifi', models.CharField(max_length=4)),
                ('carduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemStockLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('restock_date', models.DateField()),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('menu_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.orders')),
            ],
        ),
    ]
