# Generated by Django 3.1.7 on 2021-03-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='restock_quantity',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
