# Generated by Django 3.1.7 on 2021-04-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
