# Generated by Django 3.1.7 on 2021-03-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='custid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='custname',
            field=models.CharField(default='bob', max_length=150),
            preserve_default=False,
        ),
    ]
