# Generated by Django 3.1.7 on 2021-03-04 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_delete_itemstocklevels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStockLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('restock_date', models.DateField()),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredients')),
            ],
        ),
    ]
