# Generated by Django 3.1.7 on 2021-03-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210321_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
