# Generated by Django 3.1.7 on 2021-03-28 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_orders_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('stocklevel', models.IntegerField()),
                ('ingredient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredients')),
            ],
        ),
    ]
