# Generated by Django 3.1.7 on 2021-04-08 13:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_delete_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('date_consumed_stock', models.DateField(default=datetime.date.today, primary_key=True, serialize=False)),
                ('stocklevel', models.IntegerField()),
                ('ingredient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredients')),
            ],
            options={
                'unique_together': {('date_consumed_stock', 'ingredient_id')},
            },
        ),
    ]
