# Generated by Django 3.1.7 on 2021-03-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210304_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://cdn.discordapp.com/attachments/798661624181293086/820820581439897600/calzone-926449_1920.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
